export const SUBTRACT_FROM_PRICE = 'SUBTRACT_FROM_PRICE';
export const ADD_TO_PRICE = 'ADD_TO_PRICE';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'DELETE_INGREDIENT';